In [3]:
import pandas as pd
import numpy as np

#For visualization
import matplotlib.pyplot as plt

In [4]:
file = 'training_sample.tsv'

In [5]:
column_names = ["text_tokens", "hashtags", "tweet_id", "present_media", "present_links", "present_domains",
                "tweet_type", "language", "tweet_timestamp", "engaged_with_user_id", "engaged_with_user_follower_count",
               "engaged_with_user_following_count", "engaged_with_user_is_verified", "engaged_with_user_account_creation",
               "engaging_user_id", "engaging_user_follower_count", "engaging_user_following_count", "engaging_user_is_verified",
               "engaging_user_account_creation", "engaged_follows_engaging", "reply_timestamp", "retweet_timestamp", "retweet_with_comment_timestamp", "like_timestamp"]

In [6]:
df = pd.read_csv(file, delimiter='\x01')

In [7]:
df.head()

,101\t56898\t137\t174\t63247\t10526\t131\t3197\t8747\t8747\t6455\t3205\t14120\t131\t120\t120\t188\t119\t11170\t120\t176\t11090\t10305\t10686\t11211\t10116\t11127\t10237\t11779\t11517\t102,Unnamed: 1,3C21DCFB8E3FEC1CB3D2BFB413A78220,Video,Unnamed: 4,Unnamed: 5,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,1581467323,D1AA2C85FA644D64346EDD88470525F2,...,000046C8606F1C3F5A7296222C88084B,131,2105,False.1,1573978269,False.2,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,101\t102463\t10230\t10105\t21040\t10169\t12811...,NaN,3D87CC3655C276F1771752081423B405,NaN,BB422AA00380E45F312FD2CAA75F4960,92D397F8E0F1E77B36B8C612C2C51E23,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1580975391,4DC65AC7BD963DE1F7617C047C33DE99,...,00006047187D0D18598EF12A650E1DAC,22,50,False,1340673962,False,NaN,NaN,NaN,NaN
1,101\t56898\t137\t11255\t22037\t10263\t168\t111...,DB32BD91C2F1B37BE700F374A07FBC61,3701848B96AA740528A2B0E247777D7D,NaN,2423BA02A75DB2189335DDC3FB6B74A1,6D323BE93766E79BE423FAC5C28BE39B,Retweet,22C448FF81263D4BAF2A176145EE9EAD,1581257232,5C671539CB41B9807E209349B101E9FF,...,0000648BAA193AE4C625DDF789B57172,251,719,False,1456473671,False,NaN,NaN,NaN,NaN
2,101\t13073\t28757\t106\t100\t14120\t131\t120\t...,NaN,18176C6AD2871729384062F073CCE94D,Video,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581164292,70B900BE17416923D1E236A38798F202,...,000071667F50BAFEA722A8E8284581E5,18,58,False,1378427564,False,NaN,NaN,NaN,1.581305e+09
3,101\t3460\t1923\t6632\t2824\t30368\t2179\t1881...,NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,1581233650,E94C0E9E8494F3D603F9D1A5C5242E3D,...,00007745A6EE969F1A0F44B10DC17671,268,526,False,1252294800,False,NaN,NaN,NaN,NaN
4,101\t46242\t40751\t161\t100062\t10107\t10114\t...,NaN,4EC1C41302B820B2459337FE31859B16,NaN,BB79CD318A68247B64F0E0BE7AFD5A92,3896E26D12C903F0A00B6B1BE9A9BEA3,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581426841,959F94011E65010724E85D1B5CBAE18F,...,00008C78BF1DDCC9FDCBAFFAF318A175,34,36,False,1538872824,False,NaN,NaN,NaN,NaN

In [8]:
df = pd.read_csv(file, header=None, names=column_names, delimiter='\x01')

In [9]:
pd.set_option('display.max_columns', None)
print(df.shape)
display(df.head())

(80425, 24)

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,101\t56898\t137\t174\t63247\t10526\t131\t3197\...,NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,Video,NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,1581467323,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,1573978269,False,NaN,NaN,NaN,NaN
1,101\t102463\t10230\t10105\t21040\t10169\t12811...,NaN,3D87CC3655C276F1771752081423B405,NaN,BB422AA00380E45F312FD2CAA75F4960,92D397F8E0F1E77B36B8C612C2C51E23,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1580975391,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,1340673962,False,NaN,NaN,NaN,NaN
2,101\t56898\t137\t11255\t22037\t10263\t168\t111...,DB32BD91C2F1B37BE700F374A07FBC61,3701848B96AA740528A2B0E247777D7D,NaN,2423BA02A75DB2189335DDC3FB6B74A1,6D323BE93766E79BE423FAC5C28BE39B,Retweet,22C448FF81263D4BAF2A176145EE9EAD,1581257232,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,1456473671,False,NaN,NaN,NaN,NaN
3,101\t13073\t28757\t106\t100\t14120\t131\t120\t...,NaN,18176C6AD2871729384062F073CCE94D,Video,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581164292,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,1378427564,False,NaN,NaN,NaN,1.581305e+09
4,101\t3460\t1923\t6632\t2824\t30368\t2179\t1881...,NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,1581233650,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,1252294800,False,NaN,NaN,NaN,NaN

Parse attributes containing tab-separated lists into lists. Transform raw timestamps into human-readable timestamps.

In [10]:
df['text_tokens'] = df['text_tokens'].str.split('\t')

def to_hex_list(x):
    output = str(x).split('\t')
#     output = [int(val, 16) for val in str(x).split('\t')]
    return output

cols_to_process = ['hashtags', 'present_media', 'present_links', 'present_domains']

for col in cols_to_process:
    df[col] = df[col].apply(lambda x: to_hex_list(x) if isinstance(x, str)  else x)



cols_to_process = ['tweet_timestamp', 'engaging_user_account_creation', 'reply_timestamp', 'retweet_timestamp', 'retweet_with_comment_timestamp', 'like_timestamp']

for col in cols_to_process:
    df[col] = df[col].apply(lambda x: pd.Timestamp(x, unit='s'))

In [11]:
display(df.head())

,text_tokens,hashtags,tweet_id,present_media,present_links,present_domains,tweet_type,language,tweet_timestamp,engaged_with_user_id,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_id,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaging_user_account_creation,engaged_follows_engaging,reply_timestamp,retweet_timestamp,retweet_with_comment_timestamp,like_timestamp
0,"[101, 56898, 137, 174, 63247, 10526, 131, 3197...",NaN,3C21DCFB8E3FEC1CB3D2BFB413A78220,[Video],NaN,NaN,Retweet,76B8A9C3013AE6414A3E6012413CDC3B,2020-02-12 00:28:43,D1AA2C85FA644D64346EDD88470525F2,737,706,False,1403069820,000046C8606F1C3F5A7296222C88084B,131,2105,False,2019-11-17 08:11:09,False,NaT,NaT,NaT,NaT
1,"[101, 102463, 10230, 10105, 21040, 10169, 1281...",NaN,3D87CC3655C276F1771752081423B405,NaN,[BB422AA00380E45F312FD2CAA75F4960],[92D397F8E0F1E77B36B8C612C2C51E23],TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-06 07:49:51,4DC65AC7BD963DE1F7617C047C33DE99,52366425,2383,True,1230139136,00006047187D0D18598EF12A650E1DAC,22,50,False,2012-06-26 01:26:02,False,NaT,NaT,NaT,NaT
2,"[101, 56898, 137, 11255, 22037, 10263, 168, 11...",[DB32BD91C2F1B37BE700F374A07FBC61],3701848B96AA740528A2B0E247777D7D,NaN,[2423BA02A75DB2189335DDC3FB6B74A1],[6D323BE93766E79BE423FAC5C28BE39B],Retweet,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 14:07:12,5C671539CB41B9807E209349B101E9FF,988,167,False,1530094483,0000648BAA193AE4C625DDF789B57172,251,719,False,2016-02-26 08:01:11,False,NaT,NaT,NaT,NaT
3,"[101, 13073, 28757, 106, 100, 14120, 131, 120,...",NaN,18176C6AD2871729384062F073CCE94D,[Video],NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,2020-02-08 12:18:12,70B900BE17416923D1E236A38798F202,1228134,5413,False,1378699943,000071667F50BAFEA722A8E8284581E5,18,58,False,2013-09-06 00:32:44,False,NaT,NaT,NaT,2020-02-10 03:29:24
4,"[101, 3460, 1923, 6632, 2824, 30368, 2179, 188...",NaN,AF11AF01F842E7F120667B7B0B38676D,NaN,NaN,NaN,Quote,22C448FF81263D4BAF2A176145EE9EAD,2020-02-09 07:34:10,E94C0E9E8494F3D603F9D1A5C5242E3D,73,299,False,1549054499,00007745A6EE969F1A0F44B10DC17671,268,526,False,2009-09-07 03:40:00,False,NaT,NaT,NaT,NaT

### Enhance dataset with derived columns

**Task: Construct data**\
This task includes constructive data preparation operations such as the
production of derived attributes, entire new records or transformed
values for existing attributes.

**Outputs: Derived attributes**\
## Independent variables
The following new variables were defined in the dataframe:

| Name | Type | Description |
| --- | --- | --- |
| has_media | bool | Indicates that is there any media type related to the tweet or not? (should be omitted later, it was just a helper for further extraction) |
| cnt_Photo | Integer | number of photo media in the tweet |
| cnt_Video | Integer | number of video media in the tweet|
| cnt_GIF | Integer | number of GIF media in the tweet |
| cnt_Other_media | Integer | (maybe it's impossible) if there is an unknown media type, it will be counted |
| cnt_Hashtags | Integer | Count the number of hashtags in each tweet |
| cnt_Domains | Integer | Count the number of domains in each tweet |
| cnt_Links | Integer | Count the number of links in each tweet |
| cnt_Words_In_Tweet | Integer | Count the number of words in the tweet |

## Labels
| Name | Type | Description |
| --- | --- | --- |
| is_like | bool | indicates that was there a like by the engaging user on the tweet (decided on that is there timestamp exists or not) |
| is_reply | bool | indicates that was there a reply by the engaging user on the tweet (decided on that is there timestamp exists or not) |
| is_retweet | bool | indicates that was there a retweet by the engaging user on the tweet (decided on that is there timestamp exists or not) |
| is_retweet_with_comment | bool | indicates that was there a retweet with comment by the engaging user on the tweet (decided on that is there timestamp exists or not) |

## Further Ideas to variable extraction:
Edit the following table if you want to propose new attribute

| Name | Type | Description |
| --- | --- | --- |
| attribute_name |attribute_type  | attribute_description |

Is there any media in the cell?

In [12]:
df['has_media'] = df['present_media'].notna()

Count the different media types for every tweet then insert into lists

In [13]:
photoCnt = []
videoCnt = []
gifCnt = []
other = []
for d,b in zip(df['present_media'],  df['has_media']):
    if b is True:
        pht = d.count("Photo")
        video = d.count("Video")
        gif  = d.count("GIF")
        photoCnt.append(pht)
        videoCnt.append(video)
        gifCnt.append(gif)

        if len(str(d).split()) != int(pht + video + gif):
             other.append(len(str(d).split()) - int(pht + video + gif))
        else:
             other.append(0)
    else:
        photoCnt.append(0)
        videoCnt.append(0)
        gifCnt.append(0)
        other.append(0)

Create new columns based on the media-counter lists

In [14]:
df['cnt_Photo'] = photoCnt
df['cnt_Video'] = videoCnt
df['cnt_GIF'] = gifCnt
df['cnt_Other_Media'] = other

Count the number of hashtags, links and domains in each tweet

In [15]:
df['cnt_Hashtags'] = df.apply(lambda x : len(str(x['hashtags']).split()) if str(x['hashtags']) != "nan" else 0,axis=1)

df['cnt_Links'] = df.apply(lambda x : len(str(x['present_links']).split()) if str(x['present_links']) != "nan" else 0,axis=1)

df['cnt_Domains'] = df.apply(lambda x : len(str(x['present_domains']).split()) if str(x['present_domains']) != "nan" else 0,axis=1)

Count the number of words in the tweet

It is also worth to mention, that there are separators in the text with ID [101], [131], [102] (but at least 2 separator in each tweet)

In [16]:
df['cnt_Words_In_Tweet'] = df.apply(lambda x : len(str(x['text_tokens']).split()) if str(x['text_tokens']) != "nan" else 0,axis=1)

Describe some data about the number of words in the tweets
- Average number of words
- Minimum number of words
- Maximum number of words

In [17]:
np.mean(df['cnt_Words_In_Tweet'])

np.min(df['cnt_Words_In_Tweet'])

np.max(df['cnt_Words_In_Tweet'])

255

Explore the correlation between the new numeric attributes: Number Words in Tweet, Number of Hashtags, Number Of Links
, Number of Domains

In [18]:
dfCountToPlot = df[['cnt_Words_In_Tweet', 'cnt_Hashtags',  'cnt_Links', 'cnt_Domains']]

In [19]:
dfCountToPlot.corr()

                    cnt_Words_In_Tweet  cnt_Hashtags  cnt_Links  cnt_Domains
cnt_Words_In_Tweet            1.000000      0.328732   0.260528     0.260528
cnt_Hashtags                  0.328732      1.000000   0.131472     0.131472
cnt_Links                     0.260528      0.131472   1.000000     1.000000
cnt_Domains                   0.260528      0.131472   1.000000     1.000000

Between Number Of links in tweet and number of domains in tweet perfect correlation can be explored

In [20]:
df.corr()

,engaged_with_user_follower_count,engaged_with_user_following_count,engaged_with_user_is_verified,engaged_with_user_account_creation,engaging_user_follower_count,engaging_user_following_count,engaging_user_is_verified,engaged_follows_engaging,has_media,cnt_Photo,cnt_Video,cnt_GIF,cnt_Other_Media,cnt_Hashtags,cnt_Links,cnt_Domains,cnt_Words_In_Tweet
engaged_with_user_follower_count,1.000000,0.093223,0.308682,-0.235955,-0.024451,-0.035561,-0.005888,-0.143131,0.030339,-0.008244,0.051805,-0.010838,NaN,-0.001936,0.054918,0.054918,-0.001103
engaged_with_user_following_count,0.093223,1.000000,0.058721,-0.069561,0.010356,0.032920,-0.000062,0.044668,-0.026800,-0.022214,-0.008841,-0.005961,NaN,-0.007913,0.025820,0.025820,-0.010673
engaged_with_user_is_verified,0.308682,0.058721,1.000000,-0.500664,-0.036397,-0.059831,0.030250,-0.417194,0.020849,-0.032135,0.041479,-0.002380,NaN,0.071774,0.217037,0.217037,0.077791
engaged_with_user_account_creation,-0.235955,-0.069561,-0.500664,1.000000,0.005309,0.011675,-0.042345,0.305142,0.040212,0.064025,0.013990,-0.001565,NaN,0.017783,-0.178890,-0.178890,-0.028455
engaging_user_follower_count,-0.024451,0.010356,-0.036397,0.005309,1.000000,0.423069,0.183068,0.132183,-0.020403,-0.008903,-0.010653,-0.003417,NaN,-0.017025,-0.017831,-0.017831,-0.011829
engaging_user_following_count,-0.035561,0.032920,-0.059831,0.011675,0.423069,1.000000,0.044631,0.118402,-0.025263,-0.017410,-0.004377,-0.006125,NaN,-0.023859,-0.021941,-0.021941,-0.001430
engaging_user_is_verified,-0.005888,-0.000062,0.030250,-0.042345,0.183068,0.044631,1.000000,0.021150,-0.009730,-0.010408,-0.002631,0.004247,NaN,-0.004713,0.001839,0.001839,-0.009680
engaged_follows_engaging,-0.143131,0.044668,-0.417194,0.305142,0.132183,0.118402,0.021150,1.000000,-0.086642,-0.032254,-0.049564,-0.016914,NaN,-0.074455,-0.152791,-0.152791,-0.104326
has_media,0.030339,-0.026800,0.020849,0.040212,-0.020403,-0.025263,-0.009730,-0.086642,1.000000,0.617895,0.440781,0.135397,NaN,0.144969,-0.022146,-0.022146,0.159832
cnt_Photo,-0.008244,-0.022214,-0.032135,0.064025,-0.008903,-0.017410,-0.010408,-0.032254,0.617895,1.000000,-0.166624,-0.051183,NaN,0.133570,-0.019746,-0.019746,0.121960
cnt_Video,0.051805,-0.008841,0.041479,0.013990,-0.010653,-0.004377,-0.002631,-0.049564,0.440781,-0.166624,1.000000,-0.036512,NaN,0.041218,-0.055841,-0.055841,0.065872
cnt_GIF,-0.010838,-0.005961,-0.002380,-0.001565,-0.003417,-0.006125,0.004247,-0.016914,0.135397,-0.051183,-0.036512,1.000000,NaN,0.033011,0.012163,0.012163,0.013243
cnt_Other_Media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cnt_Hashtags,-0.001936,-0.007913,0.071774,0.017783,-0.017025,-0.023859,-0.004713,-0.074455,0.144969,0.133570,0.041218,0.033011,NaN,1.000000,0.131472,0.131472,0.328732
cnt_Links,0.054918,0.025820,0.217037,-0.178890,-0.017831,-0.021941,0.001839,-0.152791,-0.022146,-0.019746,-0.055841,0.012163,NaN,0.131472,1.000000,1.000000,0.260528
cnt_Domains,0.054918,0.025820,0.217037,-0.178890,-0.017831,-0.021941,0.001839,-0.152791,-0.022146,-0.019746,-0.055841,0.012163,NaN,0.131472,1.000000,1.000000,0.260528
cnt_Words_In_Tweet,-0.001103,-0.010673,0.077791,-0.028455,-0.011829,-0.001430,-0.009680,-0.104326,0.159832,0.121960,0.065872,0.013243,NaN,0.328732,0.260528,0.260528,1.000000

Encode what kind of interactions was the engaging user did with the tweet

Decided on timestamp: if there is timestamp, the interaction has happened (True), else no (False)
- Is_reply
- Is_retweet
- is _retweet_with_comment
- Is_like

In [21]:
df['is_reply'] = df['reply_timestamp'].notna()
df['is_like'] = df['like_timestamp'].notna()
df['is_retweet_with_comment'] = df['retweet_with_comment_timestamp'].notna()
df['is_retweet'] = df['retweet_timestamp'].notna()

In [22]:
df[['reply_timestamp','is_reply', 'like_timestamp', 'is_like', 'retweet_with_comment_timestamp', 'is_retweet_with_comment','retweet_timestamp' ,'is_retweet']].head(20)

,reply_timestamp,is_reply,like_timestamp,is_like,retweet_with_comment_timestamp,is_retweet_with_comment,retweet_timestamp,is_retweet
0,NaT,False,NaT,False,NaT,False,NaT,False
1,NaT,False,NaT,False,NaT,False,NaT,False
2,NaT,False,NaT,False,NaT,False,NaT,False
3,NaT,False,2020-02-10 03:29:24,True,NaT,False,NaT,False
4,NaT,False,NaT,False,NaT,False,NaT,False
5,NaT,False,NaT,False,NaT,False,NaT,False
6,NaT,False,NaT,False,NaT,False,NaT,False
7,NaT,False,2020-02-12 22:54:31,True,NaT,False,NaT,False
8,NaT,False,NaT,False,NaT,False,NaT,False
9,NaT,False,2020-02-12 22:49:15,True,NaT,False,NaT,False
10,NaT,False,NaT,False,NaT,False,2020-02-08 10:23:25,True
11,NaT,False,2020-02-07 15:19:38,True,NaT,False,NaT,False
12,NaT,False,2020-02-09 12:05:31,True,NaT,False,NaT,False
13,NaT,False,NaT,False,NaT,False,NaT,False
14,NaT,False,2020-02-10 01:35:54,True,NaT,False,NaT,False
15,2020-02-06 01:08:19,True,NaT,False,NaT,False,NaT,False
16,NaT,False,NaT,False,NaT,False,NaT,False
17,NaT,False,2020-02-10 09:51:37,True,NaT,False,NaT,False
18,NaT,False,2020-02-08 09:53:47,True,NaT,False,NaT,False
19,NaT,False,NaT,False,NaT,False,NaT,False

Explore the data that there are duplicates

In [23]:
duplicateDFRow = df[df.duplicated(subset = ["tweet_id","engaging_user_id"] )]
print(duplicateDFRow)

Empty DataFrame
Columns: [text_tokens, hashtags, tweet_id, present_media, present_links, present_domains, tweet_type, language, tweet_timestamp, engaged_with_user_id, engaged_with_user_follower_count, engaged_with_user_following_count, engaged_with_user_is_verified, engaged_with_user_account_creation, engaging_user_id, engaging_user_follower_count, engaging_user_following_count, engaging_user_is_verified, engaging_user_account_creation, engaged_follows_engaging, reply_timestamp, retweet_timestamp, retweet_with_comment_timestamp, like_timestamp, has_media, cnt_Photo, cnt_Video, cnt_GIF, cnt_Other_Media, cnt_Hashtags, cnt_Links, cnt_Domains, cnt_Words_In_Tweet, is_reply, is_like, is_retweet_with_comment, is_retweet]
Index: []

There isn't any duplicated row based on attributes tweet_id and engaging user's id

In [24]:
#Export the dataframe to tsv
# Can be read with ' pd.read_csv('training_sample_NewAttritbutes.tsv', delimiter='\x01')'
#  like the original solution, but don't need to transform and rename columns
df.to_csv('training_sample_NewAttritbutes.tsv', sep = '\x01',index = False)

dfNew = pd.read_csv('training_sample_NewAttritbutes.tsv', delimiter='\x01')
dfNew.head(5)